package com.tang.hwplib.builder.template.emptydocument.docinfo

import com.tang.hwplib.builder.docinfo.HWPCharShapeBuilder
import com.tang.hwplib.builder.docinfo.charshape.*
import com.tang.hwplib.builder.etc.Color4ByteBuilder
import com.tang.hwplib.builder.etc.HWPDocInfoBuilderType
import com.tang.hwplib.objects.docinfo.HWPDocInfo

class HWPEmptyCharShapeBuilder {
    private fun getBuilder(docInfo: HWPDocInfo) : HWPCharShapeBuilder = docInfo.getBuilder(HWPDocInfoBuilderType.CharShape) as HWPCharShapeBuilder

    fun build(docInfo: HWPDocInfo) {
        getBuilder(docInfo).setFaceNameIDs(HWPFaceNameIDBuilder().setForAll(1))
                .setRatios(HWPRatiosBuilder().setForAll(100))
                .setCharSpaces(HWPCharSpaceBuilder().setForAll(0))
                .setRelativeSizes(HWPRelativeSizeBuilder().setForAll(100))
                .setCharOffsets(HWPCharOffsetsBuilder().setForAll(0))
                .setBaseSize(1000)
                .setProperty(HWPCharShapePropertyBuilder().setValue(0))
                .setShadowGap1(10)
                .setShadowGap2(10)
                .setCharColor(Color4ByteBuilder().setValue(0))
                .setUnderLineColor(Color4ByteBuilder().setValue(0))
                .setShadeColor(Color4ByteBuilder().setValue(-1))
                .setShadowColor(Color4ByteBuilder().setValue(11711154))
                .setBorderFillID(2)
                .setStrikeLineColor(Color4ByteBuilder().setValue(0)).build()
        getBuilder(docInfo).setFaceNameIDs(HWPFaceNameIDBuilder().setForAll(0))
                .setRatios(HWPRatiosBuilder().setForAll(100))
                .setCharSpaces(HWPCharSpaceBuilder().setForAll(0))
                .setRelativeSizes(HWPRelativeSizeBuilder().setForAll(100))
                .setCharOffsets(HWPCharOffsetsBuilder().setForAll(0))
                .setBaseSize(1000)
                .setProperty(HWPCharShapePropertyBuilder().setValue(0))
                .setShadowGap1(10)
                .setShadowGap2(10)
                .setCharColor(Color4ByteBuilder().setValue(0))
                .setUnderLineColor(Color4ByteBuilder().setValue(0))
                .setShadeColor(Color4ByteBuilder().setValue(-1))
                .setShadowColor(Color4ByteBuilder().setValue(11711154))
                .setBorderFillID(2)
                .setStrikeLineColor(Color4ByteBuilder().setValue(0)).build()
        getBuilder(docInfo).setFaceNameIDs(HWPFaceNameIDBuilder().setForAll(0))
                .setRatios(HWPRatiosBuilder().setForAll(100))
                .setCharSpaces(HWPCharSpaceBuilder().setForAll(0))
                .setRelativeSizes(HWPRelativeSizeBuilder().setForAll(100))
                .setCharOffsets(HWPCharOffsetsBuilder().setForAll(0))
                .setBaseSize(900)
                .setProperty(HWPCharShapePropertyBuilder().setValue(0))
                .setShadowGap1(10)
                .setShadowGap2(10)
                .setCharColor(Color4ByteBuilder().setValue(0))
                .setUnderLineColor(Color4ByteBuilder().setValue(0))
                .setShadeColor(Color4ByteBuilder().setValue(-1))
                .setShadowColor(Color4ByteBuilder().setValue(11711154))
                .setBorderFillID(2)
                .setStrikeLineColor(Color4ByteBuilder().setValue(0)).build()
        getBuilder(docInfo).setFaceNameIDs(HWPFaceNameIDBuilder().setForAll(1))
                .setRatios(HWPRatiosBuilder().setForAll(100))
                .setCharSpaces(HWPCharSpaceBuilder().setForAll(0))
                .setRelativeSizes(HWPRelativeSizeBuilder().setForAll(100))
                .setCharOffsets(HWPCharOffsetsBuilder().setForAll(0))
                .setBaseSize(900)
                .setProperty(HWPCharShapePropertyBuilder().setValue(0))
                .setShadowGap1(10)
                .setShadowGap2(10)
                .setCharColor(Color4ByteBuilder().setValue(0))
                .setUnderLineColor(Color4ByteBuilder().setValue(0))
                .setShadeColor(Color4ByteBuilder().setValue(-1))
                .setShadowColor(Color4ByteBuilder().setValue(11711154))
                .setBorderFillID(2)
                .setStrikeLineColor(Color4ByteBuilder().setValue(0)).build()
        getBuilder(docInfo).setFaceNameIDs(HWPFaceNameIDBuilder().setForAll(0))
                .setRatios(HWPRatiosBuilder().setForAll(100))
                .setCharSpaces(HWPCharSpaceBuilder().setForAll(-5))
                .setRelativeSizes(HWPRelativeSizeBuilder().setForAll(100))
                .setCharOffsets(HWPCharOffsetsBuilder().setForAll(0))
                .setBaseSize(900)
                .setProperty(HWPCharShapePropertyBuilder().setValue(0))
                .setShadowGap1(10)
                .setShadowGap2(10)
                .setCharColor(Color4ByteBuilder().setValue(0))
                .setUnderLineColor(Color4ByteBuilder().setValue(0))
                .setShadeColor(Color4ByteBuilder().setValue(-1))
                .setShadowColor(Color4ByteBuilder().setValue(11711154))
                .setBorderFillID(2)
                .setStrikeLineColor(Color4ByteBuilder().setValue(0)).build()
        getBuilder(docInfo).setFaceNameIDs(HWPFaceNameIDBuilder().setForAll(0))
                .setRatios(HWPRatiosBuilder().setForAll(100))
                .setCharSpaces(HWPCharSpaceBuilder().setForAll(0))
                .setRelativeSizes(HWPRelativeSizeBuilder().setForAll(100))
                .setCharOffsets(HWPCharOffsetsBuilder().setForAll(0))
                .setBaseSize(1600)
                .setProperty(HWPCharShapePropertyBuilder().setValue(0))
                .setShadowGap1(10)
                .setShadowGap2(10)
                .setCharColor(Color4ByteBuilder().setValue(11891758))
                .setUnderLineColor(Color4ByteBuilder().setValue(0))
                .setShadeColor(Color4ByteBuilder().setValue(-1))
                .setShadowColor(Color4ByteBuilder().setValue(11711154))
                .setBorderFillID(2)
                .setStrikeLineColor(Color4ByteBuilder().setValue(0)).build()
        getBuilder(docInfo).setFaceNameIDs(HWPFaceNameIDBuilder().setForAll(0))
                .setRatios(HWPRatiosBuilder().setForAll(100))
                .setCharSpaces(HWPCharSpaceBuilder().setForAll(0))
                .setRelativeSizes(HWPRelativeSizeBuilder().setForAll(100))
                .setCharOffsets(HWPCharOffsetsBuilder().setForAll(0))
                .setBaseSize(1100)
                .setProperty(HWPCharShapePropertyBuilder().setValue(0))
                .setShadowGap1(10)
                .setShadowGap2(10)
                .setCharColor(Color4ByteBuilder().setValue(0))
                .setUnderLineColor(Color4ByteBuilder().setValue(0))
                .setShadeColor(Color4ByteBuilder().setValue(-1))
                .setShadowColor(Color4ByteBuilder().setValue(11711154))
                .setBorderFillID(2)
                .setStrikeLineColor(Color4ByteBuilder().setValue(0)).build()
    }
}