package com.tang.hwplib.builder.template.emptydocument.docinfo

import com.tang.hwplib.builder.docinfo.HWPStyleBuilder
import com.tang.hwplib.builder.docinfo.HWPStyleListBuilder
import com.tang.hwplib.builder.docinfo.style.HWPStylePropertyBuilder
import com.tang.hwplib.builder.etc.HWPDocInfoBuilderType
import com.tang.hwplib.builder.interfaces.HWPBuilder
import com.tang.hwplib.objects.docinfo.HWPDocInfo
import com.tang.hwplib.objects.docinfo.HWPStyle

class HWPEmptyStyleBuilder {
    private fun getBuilder(docInfo: HWPDocInfo) : HWPStyleBuilder = docInfo.builderFactory(HWPDocInfoBuilderType.Style) as HWPStyleBuilder
    fun build(docInfo: HWPDocInfo) {
        getBuilder(docInfo)
                .setHangulName("바탕글")
                .setEnglishName("Normal")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setLanguageID(1042)
                .setParaShapeId(3).build()
        getBuilder(docInfo)
                .setHangulName("본문")
                .setEnglishName("Body")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(1)
                .setLanguageID(1042)
                .setParaShapeId(11).build()
        getBuilder(docInfo)
                .setHangulName("개요 1")
                .setEnglishName("Outline 1")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(2)
                .setLanguageID(1042)
                .setParaShapeId(10).build()
        getBuilder(docInfo)
                .setHangulName("개요 2")
                .setEnglishName("Outline 2")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(3)
                .setLanguageID(1042)
                .setParaShapeId(9).build()
        getBuilder(docInfo)
                .setHangulName("개요 3")
                .setEnglishName("Outline 3")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(4)
                .setLanguageID(1042)
                .setParaShapeId(8).build()
        getBuilder(docInfo)
                .setHangulName("개요 4")
                .setEnglishName("Outline 4")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(5)
                .setLanguageID(1042)
                .setParaShapeId(7).build()
        getBuilder(docInfo)
                .setHangulName("개요 5")
                .setEnglishName("Outline 5")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(6)
                .setLanguageID(1042)
                .setParaShapeId(6).build()
        getBuilder(docInfo)
                .setHangulName("개요 6")
                .setEnglishName("Outline 6")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(7)
                .setLanguageID(1042)
                .setParaShapeId(5).build()
        getBuilder(docInfo)
                .setHangulName("개요 7")
                .setEnglishName("Outline 7")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(8)
                .setLanguageID(1042)
                .setParaShapeId(4).build()
        getBuilder(docInfo)
                .setHangulName("쪽 번호")
                .setEnglishName("Page Number")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(9)
                .setLanguageID(1042)
                .setCharShapeID(1).build()
        getBuilder(docInfo)
                .setHangulName("머리말")
                .setEnglishName("Header")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(10)
                .setLanguageID(1042)
                .setParaShapeId(2)
                .setCharShapeID(2).build()
        getBuilder(docInfo)
                .setHangulName("각주")
                .setEnglishName("Footnote")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(11)
                .setLanguageID(1042)
                .setParaShapeId(1)
                .setCharShapeID(3).build()
        getBuilder(docInfo)
                .setHangulName("미주")
                .setEnglishName("Endnote")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(12)
                .setLanguageID(1042)
                .setParaShapeId(1)
                .setCharShapeID(3).build()
        getBuilder(docInfo)
                .setHangulName("메모")
                .setEnglishName("Memo")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(13)
                .setLanguageID(1042)
                .setParaShapeId(0)
                .setCharShapeID(4).build()
        getBuilder(docInfo)
                .setHangulName("차례 제목")
                .setEnglishName("TOC Heading")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(14)
                .setLanguageID(1042)
                .setParaShapeId(12)
                .setCharShapeID(5).build()
        getBuilder(docInfo)
                .setHangulName("차례 1")
                .setEnglishName("TOC 1")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(15)
                .setLanguageID(1042)
                .setParaShapeId(13)
                .setCharShapeID(6).build()
        getBuilder(docInfo)
                .setHangulName("차례 2")
                .setEnglishName("TOC 2")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(16)
                .setLanguageID(1042)
                .setParaShapeId(14)
                .setCharShapeID(6).build()
        getBuilder(docInfo)
                .setHangulName("차례 3")
                .setEnglishName("TOC 3")
                .setProperty(HWPStylePropertyBuilder().setValue(0))
                .setNextStyleID(17)
                .setLanguageID(1042)
                .setParaShapeId(15)
                .setCharShapeID(6).build()
    }
}